syntax = "proto3";


message LoginRequest {
    string username = 1;  
    string password = 2;  
}


message LoginResponse {
    string token = 1;     
    int32 user_id = 2;    
    string message = 3;   
}


message User {
    int32 id = 1;           
    string username = 2;    
    string email = 3;       
    string full_name = 4;   
}


message GetProfileRequest {
    int32 user_id = 1;  
}


message GetProfileResponse {
    User user = 1;      
    string error = 2;   
}


message UpdateProfileRequest {
    int32 user_id = 1;      
    string email = 2;       
    string full_name = 3;   
}


message UpdateProfileResponse {
    bool success = 1;    
    string message = 2;  
}


service UserService {
    
    rpc Login(LoginRequest) returns (LoginResponse);
    
    
    rpc GetProfile(GetProfileRequest) returns (GetProfileResponse);
    
    
    rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse);
}